repos:

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.1.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        files: "^(?!examples/)"
        args: ["--application-directories", ".:src"]

  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["-S"]

  # TODO: Use flake8 + bugbear.

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
