dist: bionic

language: python

python:
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"
    # TODO: Build for pypy3.6 when it's released.
    #- "pypy3.6"

matrix:
    allow_failures:
        # https://travis-ci.org/lemon24/reader/jobs/534208497
        - python: "3.8-dev"
        - python: "nightly"

install:
    - make install-dev
    - pip install codecov

script: make coverage

notifications:
    email: false

after_success:
    - codecov
