dist: bionic

language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"
    - "3.9"
    - "nightly"
    - "pypy3"  # 3.6, per https://docs.travis-ci.com/user/languages/python/#pypy-support


matrix:
    allow_failures:
        - python: "3.9-dev"
        - python: "3.9"
        - python: "nightly"

install:
    - make install-dev
    - pip install codecov

script: make coverage typing

notifications:
    email: false

after_success:
    - codecov
