
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        python-version: [
          "3.7", "3.8", "3.9", "3.10",
          # PyPy 7.3.8 has a very old version of SQLite
          # https://github.com/actions/setup-python/issues/339
          # https://foss.heptapod.net/pypy/pypy/-/issues/3690
          "pypy-3.7-v7.3.7",
          "pypy-3.8-v7.3.7",
        ]
        os: [ubuntu-latest, macos-latest, windows-latest]

        exclude:
          - os: windows-latest
            python-version: "3.7"
          - os: windows-latest
            python-version: "pypy-3.7-v7.3.7"
          - os: windows-latest
            python-version: "3.8"
          - os: windows-latest
            python-version: "pypy-3.8-v7.3.7"

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: ./run.sh ci-install
      - run: ./run.sh ci-run

      - uses: codecov/codecov-action@v1.5.0
